services:
    creonit_admin:
        public: true
        class: Creonit\AdminBundle\Manager
        arguments:
            - '@service_container'
            - '@twig'

    Creonit\AdminBundle\Manager:
        alias: creonit_admin

    Creonit\AdminBundle\Controller\:
        autowire: true
        autoconfigure: true
        resource: '../../Controller'
        tags: ['controller.service_arguments']
